import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.dirname(fileURLToPath(import.meta.url));
const languages = ['zh-CN','en','es','fr','de','ja','pt-BR'];
const catalogs = Object.fromEntries(languages.map(language => [language, {}]));
for (const file of fs.readdirSync(path.join(root, 'locales')).filter(file => file.endsWith('.tsv'))) {
  for (const [index, row] of fs.readFileSync(path.join(root,'locales',file),'utf8').split(/\r?\n/).entries()) {
    if (!row.trim()) continue;
    const values = row.split('\t').map(value => value.replaceAll('\\n','\n'));
    if (values.length !== 7 || values.some(value => !value.trim())) throw Error(`${file}:${index+1}: expected seven complete translations`);
    languages.forEach((language, i) => { catalogs[language][values[0]] = values[i]; });
  }
}
fs.writeFileSync(path.join(root,'dist/locales.js'), 'window.YUE_LOCALES = ' + JSON.stringify(catalogs) + ';\n');
const nativeArgument = process.argv.indexOf('--native');
if (nativeArgument >= 0) {
  const destination=path.resolve(process.argv[nativeArgument+1]);
  const nativeKeys=fs.readFileSync(path.join(root,'locales/native.tsv'),'utf8').split(/\r?\n/).filter(Boolean).map(row=>row.split('\t')[0].replaceAll('\\n','\n'));
  nativeKeys.push('阅 · Markdown 阅读器','语言');
  const rows=[...new Set(nativeKeys)].map(key=>'            { '+JSON.stringify(key)+', new string[] { '+languages.map(language=>JSON.stringify(catalogs[language][key])).join(', ')+' } }');
  fs.writeFileSync(destination,'// Generated by md-reader/build-locales.mjs --native.\nnamespace YueReader { public static partial class L {\n        static readonly System.Collections.Generic.Dictionary<string, string[]> Translations = new System.Collections.Generic.Dictionary<string, string[]> {\n'+rows.join(',\n')+'\n        };\n} }\n');
}
console.log(`${Object.keys(catalogs.en).length} strings × ${languages.length} languages`);
export { catalogs };
